### ISSUE TITLE
[Feature request] Add `append` method to `sys.io.File` class

### ISSUE THREAD

**Issue by cedx** [HaxeFoundation/hxnodejs#165] opened 2020-05-20 08:52 UTC
I'm trying to use `mcover` package to collect the code coverage of a Node.js application.
This package is mostly compatible with `hxnodejs`... but uses the `sys.io.File.append()` method which is not implemented by `hxnodejs`:
https://github.com/HaxeFoundation/hxnodejs/blob/master/src/sys/io/File.hx

**Comment by Gama11** [comment] 2020-05-20 08:58
Duplicate of https://github.com/HaxeFoundation/hxnodejs/issues/120.

**Closed by Gama11** 2020-05-20 08:58 UTC
